module Problem2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let fib = Seq.unfold (fun state ->
    if (snd state > 4000000) then None
    else Some(fst state + snd state, (snd state, fst state + snd state))) (1,1)

let result = fib |> Seq.rev |> Seq.skip 1 |> Seq.head